include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.generated.dart"
    - "**/*.freezed.dart"

linter:
  rules:

    prefer_single_quotes: true  
    sort_pub_dependencies: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_classes_with_only_static_members: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: false
    avoid_return_types_on_setters: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_print: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    overridden_fields: true
    one_member_abstracts: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_generic_function_type_aliases: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: false
    use_rethrow_when_possible: true
    valid_regexps: true
    avoid_field_initializers_in_const_classes: false
    avoid_function_literals_in_foreach_calls: false
    avoid_empty_else: true
    cancel_subscriptions: true
    empty_statements: true
    directives_ordering: true
    empty_catches: true
    hash_and_equals: true
    list_remove_unrelated_type: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    require_trailing_commas: true
    unawaited_futures: true
    always_use_package_imports: true

