name: app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.2
  go_router: ^6.5.2
  uuid: ^3.0.7
  widget_with_codeview: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.7
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - lib/pages/
